#define IRIS_MAP_WIDTH  314
#define IRIS_MAP_HEIGHT 50

#define SCLERA_WIDTH 250
#define SCLERA_HEIGHT 250

#define SCREEN_WIDTH 160
#define SCREEN_HEIGHT 160

#define IRIS_WIDTH  100
#define IRIS_HEIGHT 100

#define SYMMETRICAL_EYELID 
