#define IRIS_MAP_WIDTH  471
#define IRIS_MAP_HEIGHT 75

#define SCLERA_WIDTH 375
#define SCLERA_HEIGHT 375

#define SCREEN_WIDTH 240
#define SCREEN_HEIGHT 240

#define IRIS_WIDTH  150
#define IRIS_HEIGHT 150

#define SYMMETRICAL_EYELID
